"""
UNIT & INTEGRATION TESTS: COINSWITCH PRO API CLIENT & SMART CHASER
===================================================================
Tests Ed25519 signature validity, NTP drift auto-correction, live read-only
orderbook and balance queries, and executes Smart Chaser mock simulations.
"""

import unittest
import os
import sys
from unittest.mock import MagicMock, patch

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from config import CONFIG
from core.exchange_client import CoinSwitchFuturesClient, SmartOrderChaser
from cryptography.hazmat.primitives.asymmetric import ed25519

class TestExchangeClient(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.client = CoinSwitchFuturesClient(config=CONFIG)

    def test_01_ed25519_key_and_signature_validity(self):
        """
        Mathematically verifies that signatures generated by our client can be verified
        by CoinSwitch's matching engine using our public key.
        """
        self.assertTrue(len(self.client.public_key_hex) == 64)
        
        # Test signature generation
        headers, path = self.client._sign_request("GET", "/trade/api/v2/futures/wallet_balance")
        sig_hex = headers["X-AUTH-SIGNATURE"]
        epoch = headers["X-AUTH-EPOCH"]
        self.assertEqual(len(sig_hex), 128)  # 64 bytes = 128 hex chars
        
        # Verify cryptographically using public key
        pub_key = ed25519.Ed25519PublicKey.from_public_bytes(bytes.fromhex(self.client.public_key_hex))
        expected_msg = f"GET{path}{epoch}".encode("utf-8")
        
        # Will raise InvalidSignature if not valid
        pub_key.verify(bytes.fromhex(sig_hex), expected_msg)

    def test_02_ntp_server_clock_drift(self):
        """
        Verifies NTP clock drift is within CoinSwitch's +/- 5000ms window.
        """
        drift = self.client.sync_clock()
        self.assertLess(abs(drift), 5000)

    def test_03_live_read_only_wallet_balance(self):
        """
        Queries live CoinSwitch wallet balance (Read-Only: $0 at risk).
        """
        bal = self.client.get_wallet_balance()
        self.assertIn("base_asset_balances", bal)

    def test_04_live_read_only_order_books(self):
        """
        Queries live order books for ETHUSDT and BTCUSDT and verifies spreads.
        """
        for sym in ["ETHUSDT", "BTCUSDT"]:
            ob = self.client.get_order_book(sym)
            bids = ob.get("bids", [])
            asks = ob.get("asks", [])
            self.assertTrue(len(bids) > 0)
            self.assertTrue(len(asks) > 0)
            best_bid = float(bids[0][0])
            best_ask = float(asks[0][0])
            self.assertGreater(best_ask, 0)
            self.assertGreater(best_bid, 0)
            spread_pct = (best_ask - best_bid) / best_bid
            self.assertLess(spread_pct, 0.005)  # Spread well under 0.5%

    def test_05_smart_chaser_immediate_fill(self):
        """
        Simulates Smart Chaser when order fills on the first 10-second check.
        """
        mock_client = MagicMock()
        mock_client.get_order_book.return_value = {
            "bids": [["2650.00", "10.0"]],
            "asks": [["2650.10", "10.0"]]
        }
        mock_client.place_limit_order.return_value = {"order_id": "ORD_12345"}
        mock_client.get_order_status.return_value = {
            "status": "FILLED",
            "average_price": "2650.00"
        }

        chaser = SmartOrderChaser(mock_client, CONFIG)
        with patch("time.sleep", return_value=None):
            result = chaser.execute_smart_limit_entry(
                symbol="ETHUSDT",
                direction=1,
                quantity=0.1,
                signal_candle_close=2649.00
            )

        self.assertTrue(result["success"])
        self.assertEqual(result["fill_price"], 2650.00)
        self.assertEqual(result["attempts"], 1)

    def test_06_smart_chaser_slippage_ceiling_guard(self):
        """
        Simulates sudden spike: price runs away > 0.35% from signal candle.
        Chaser MUST abort trade safely to prevent buying the top of a wick.
        """
        mock_client = MagicMock()
        # Price jumped to 2670 on signal 2640 (> 1.1% jump)
        mock_client.get_order_book.return_value = {
            "bids": [["2669.50", "10.0"]],
            "asks": [["2670.00", "10.0"]]
        }

        chaser = SmartOrderChaser(mock_client, CONFIG)
        result = chaser.execute_smart_limit_entry(
            symbol="ETHUSDT",
            direction=1,
            quantity=0.1,
            signal_candle_close=2640.00
        )

        self.assertFalse(result["success"])
        self.assertIn("aborted to avoid buying the wick", result["reason"])
        mock_client.place_limit_order.assert_not_called()

if __name__ == '__main__':
    unittest.main()
